version: '3.8'

services:
  app:
    image: sensores:latest
    container_name: sensores
    ports:
      - "8080:8080"
    depends_on:
      - db
#        condition: service_healthy
    networks:
      - my-network

  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - my-network
#    healthcheck:
#      test: [ "CMD-SHELL", "mariadb-admin ping -h localhost" ]
#      timeout: 5s
#      retries: 5

volumes:
  db-data:

networks:
  my-network: