version: '3.8'

services:
  app:
    image: sensores:latest
    container_name: sensores
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - my-network

  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - my-network

volumes:
  db-data:

networks:
  my-network: